## Spatially join points and polygon data

Spatially join or aggregate the number of points over each polygon in a layer and view the results in a map within the notebook. 

> NOTE: This notebook demonstrates two patterns:
> 1. The points and polygons are being accessed through __hosted service urls__
> 2. The points and polygons are being accessed through __local files (.csv or .shp) in your notebook workspace__.
> 
> Use the pattern that is appropriate for your data.

#### Import necessary libraries and connect to GIS

In [1]:
from arcgis.gis import GIS
from arcgis.features import FeatureLayer
import pandas as pd

gis = GIS("home")

You are logged on as MMajumdar_geosaurus with an administrator role, proceed with caution.

## Pattern 1: Data is accessed through service urls

#### Define inputs

In [2]:
#pattern for accessing data through service url
points_layer_url = '<POINTS-SERVICE-URL>'
polygon_layer_url = '<POLYGON-SERVICE-URL>'

#coordinate_system to access data in
coordinate_system_id = <WELL-KNOWN-ID> #integer e.g. 4326

#### Fetch the points and polygon layers

Using the `out_sr` parameter in the query ensures that both layers are rendered in the same coordinate system for ease of spatial operations.

In [3]:
points_layer = FeatureLayer(points_layer_url)
points_df = points_layer.query(as_df=True, out_sr=coordinate_system_id)
points_df.head()

,NAME,ADDRESS,PHONE,TYPE,WEB_URL,SSL,STATUS,WARD,PSA,GIS_ID,...,LATITUDE,LONGITUDE,XCOORD,YCOORD,SE_ANNO_CAD_DATA,GLOBALID,CREATED,EDITED,OBJECTID,SHAPE
0,DC Jail Library,1901 D STREET SE,<NA>,DC Jail Library,https://www.dclibrary.org/plan-visit/dc-jail-l...,1112E 0007,Open,Ward 7,Police Service Area 107,LibraryPt_33,...,38.883431,-76.976379,402049.46,135066.23,None,{4FF32F77-5B4C-4C73-9665-CF81F6521C67},2023-06-16 18:14:49,2023-06-16 18:14:49,961,"{""x"": -76.97638119145078, ""y"": 38.883438357613..."
1,Southwest Library,900 WESLEY PLACE SW,(202) 724-4752,Neighborhood Library,https://www.dclibrary.org/plan-visit/southwest...,0542 0087,Open,Ward 6,Police Service Area 105,LibraryPt_15,...,38.878698,-77.015832,398626.28,134540.69,None,{B852C18D-6766-4C60-ABE4-FA9F620378EE},2022-08-04 22:52:55,2024-11-07 21:28:57,663,"{""x"": -77.01583405701506, ""y"": 38.878705402198..."
2,Woodridge Library,1801 HAMLIN STREET NE,(202) 541-6226,Neighborhood Library,https://www.dclibrary.org/plan-visit/woodridge...,4210 0825,Open,Ward 5,Police Service Area 505,LibraryPt_22,...,38.927414,-76.978635,401852.53,139948.67,None,{9C0FC0DB-F083-459D-A65B-97D78309B437},2022-08-04 22:52:55,2024-11-07 21:28:57,644,"{""x"": -76.97862792266683, ""y"": 38.927448190696..."
3,Rosedale Library,1701 GALES STREET NE,(202) 727-5012,Neighborhood Library,https://www.dclibrary.org/plan-visit/rosedale-...,4533 0035,Open,Ward 7,Police Service Area 507,LibraryPt_32,...,38.897812,-76.979134,401810.05,136662.58,None,{3A92CB9D-4928-4F02-B39B-AC0CF994E352},2022-08-04 22:52:55,2024-11-07 21:28:57,647,"{""x"": -76.97914133730877, ""y"": 38.897820187074..."
4,Takoma Park Library,416 CEDAR STREET NW,(202) 576-7252,Neighborhood Library,https://www.dclibrary.org/plan-visit/takoma-pa...,3191 0810,Open,Ward 4,Police Service Area 401,LibraryPt_17,...,38.974437,-77.020157,398253.34,145168.59,None,{25C19CED-13C2-4C0D-BD29-F56B2C2ED49C},2022-08-04 22:52:55,2024-11-07 21:28:57,665,"{""x"": -77.02015914976741, ""y"": 38.974444213199..."

In [4]:
polygon_layer = FeatureLayer(polygon_layer_url)
polygon_df = polygon_layer.query(as_df=True, out_sr=coordinate_system_id)
polygon_df.head()

,NBH_NAMES,NAME,WEB_URL,TYPE,GIS_ID,GLOBALID,CREATED,EDITED,SHAPE.AREA,SHAPE.LEN,OBJECTID,SHAPE
0,"Deanwood, Burrville, Grant Park, Lincoln Heigh...",Cluster 31,http://planning.dc.gov/,Original,NbhClusPly_33,{84876282-0AFE-4553-8F28-958497FC1A4C},NaT,NaT,0.0,0.0,33,"{""rings"": [[[-76.91321985185806, 38.8897639240..."
1,"Mayfair, Hillbrook, Mahaning Heights",Cluster 30,http://planning.dc.gov/,Original,NbhClusPly_34,{ACAF18C8-CC07-471C-A0B2-DE7DDCF92445},NaT,NaT,0.0,0.0,34,"{""rings"": [[[-76.94754729749613, 38.9059742613..."
2,"West End, Foggy Bottom, GWU",Cluster 5,http://planning.dc.gov/,Original,NbhClusPly_35,{B064E40A-40A8-49F7-B5FE-D96ED849A117},NaT,NaT,0.0,0.0,35,"{""rings"": [[[-77.05011148344563, 38.9089854271..."
3,"Union Station, Stanton Park, Kingman Park",Cluster 25,http://planning.dc.gov/,Original,NbhClusPly_36,{AD1842F5-5804-470D-B507-D7B47BE4DF87},NaT,NaT,0.0,0.0,36,"{""rings"": [[[-76.98440099158206, 38.9003204948..."
4,"Downtown, Chinatown, Penn Quarters, Mount Vern...",Cluster 8,http://planning.dc.gov/,Original,NbhClusPly_37,{ABEB56A6-5C60-4D3D-9248-CB56BEA2F308},NaT,NaT,0.0,0.0,37,"{""rings"": [[[-77.00905554018836, 38.9056572662..."

#### Spatially join the two layers

In [5]:
joined = polygon_df.spatial.join(points_df, how='left')
joined.head()

,NBH_NAMES,NAME_left,WEB_URL_left,TYPE_left,GIS_ID_left,GLOBALID_left,CREATED_left,EDITED_left,SHAPE.AREA,SHAPE.LEN,...,MAR_ID,LATITUDE,LONGITUDE,XCOORD,YCOORD,SE_ANNO_CAD_DATA,GLOBALID_right,CREATED_right,EDITED_right,OBJECTID_right
0,"Deanwood, Burrville, Grant Park, Lincoln Heigh...",Cluster 31,http://planning.dc.gov/,Original,NbhClusPly_33,{84876282-0AFE-4553-8F28-958497FC1A4C},NaT,NaT,0.0,0.0,...,307551.0,38.908445,-76.932156,405884.39,137844.91,None,{13667145-1D58-4D2A-8673-DF465E87D013},2022-08-04 22:52:55,2024-11-07 21:28:57,652
1,"Mayfair, Hillbrook, Mahaning Heights",Cluster 30,http://planning.dc.gov/,Original,NbhClusPly_34,{ACAF18C8-CC07-471C-A0B2-DE7DDCF92445},NaT,NaT,0.0,0.0,...,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,NaT,NaT,<NA>
2,"West End, Foggy Bottom, GWU",Cluster 5,http://planning.dc.gov/,Original,NbhClusPly_35,{B064E40A-40A8-49F7-B5FE-D96ED849A117},NaT,NaT,0.0,0.0,...,242337.0,38.903966,-77.05063,395608.43,137346.76,None,{F9AEFAC8-9122-4A43-A2CA-6D91A2454062},2022-08-04 22:52:55,2024-11-07 21:28:57,643
3,"Union Station, Stanton Park, Kingman Park",Cluster 25,http://planning.dc.gov/,Original,NbhClusPly_36,{AD1842F5-5804-470D-B507-D7B47BE4DF87},NaT,NaT,0.0,0.0,...,37106.0,38.894409,-76.99643,400309.69,136284.61,None,{BEF20C6C-EC60-4037-A375-303ED95B60F1},2022-08-04 22:52:55,2024-11-07 21:28:57,659
4,"Union Station, Stanton Park, Kingman Park",Cluster 25,http://planning.dc.gov/,Original,NbhClusPly_36,{AD1842F5-5804-470D-B507-D7B47BE4DF87},NaT,NaT,0.0,0.0,...,307101.0,38.897812,-76.979134,401810.05,136662.58,None,{3A92CB9D-4928-4F02-B39B-AC0CF994E352},2022-08-04 22:52:55,2024-11-07 21:28:57,647

* Alternatively, you can also use the `aggregate_points()` analysis tool by clicking on `Analysis` in the top ribbon of the notebook editor, and clicking `Add` for the `Aggregate points` tool. Note that usage of this tool consumes credits in ArcGIS Online.

Once added you can populate it as shown below:

In [6]:
result_layer_title = '<OUTPUT-NAME>'

In [7]:
from arcgis import features
joined_layer = features.summarize_data.aggregate_points(points_layer, polygon_layer, output_name=result_layer_title, gis=gis)
joined_layer

{"cost": 0.074}

#### Plotting on a map

In [8]:
map1 = gis.map()
map1.content.add(joined_layer)
map1.zoom_to_layer(joined_layer)
map1

Map(extent={'xmin': -8584909.685738908, 'ymin': 4691862.387048862, 'xmax': -8561472.787091771, 'ymax': 4721090…

## Pattern 2: Data is accessed through .CSV or .SHP files in your workspace directory

#### Define inputs

In [ ]:
#pattern for accessing data through both .csv or .shp files
path_to_points_data = '<PATH-TO-YOUR-POINTS-CSV>' 
path_to_polygon_data = '<PATH-TO-YOUR-POLYGON-SHP>'

#coordinate_system to access data in
coordinate_system_id = <WELL_KNOWN_ID> #integer e.g. 4326

#column names for the .csv file
points_data_x_column_name = '<COLUMN-NAME-FOR-LONGITUDE-COLUMN>'
points_data_y_column_name = '<COLUMN-NAME-FOR-LATITUDE-COLUMN>'

#### Read in the .CSV points data

In [ ]:
df1 = pd.read_csv(path_to_points_data)
sedf_points = pd.DataFrame.spatial.from_xy(df1, x_column = points_data_x_column_name, y_column = points_data_y_column_name, sr = coordinate_system_id)
sedf_points.head()

#### Read in the .SHP polygon data

In [11]:
sedf_polygon = pd.DataFrame.spatial.from_featureclass(location=path_to_polygon_data)
sedf_polygon.head()

,FID,NBH_NAMES,NAME,WEB_URL,TYPE,GIS_ID,GLOBALID,CREATED,EDITED,OBJECTID,SHAPEAREA,SHAPELEN,SHAPE
0,0,"Colonial Village, Shepherd Park, North Portal ...",Cluster 16,http://planning.dc.gov/,Original,NbhClusPly_1,{8D235E97-D58C-4891-943E-307143103BD9},,,1,0,0,"{""rings"": [[[-8574749.706027592, 4719677.35010..."
1,1,Rock Creek Park,Cluster 41,,Additional,NbhClusPly_2,{939C23A8-8EE2-4B4F-85EE-88281BCCC9A0},,,2,0,0,"{""rings"": [[[-8576489.194073, 4719425.79052275..."
2,2,"Hawthorne, Barnaby Woods, Chevy Chase",Cluster 10,http://planning.dc.gov/,Original,NbhClusPly_3,{8EADC8B8-3DAD-4E5D-AAF8-BF63D8316317},,,3,0,0,"{""rings"": [[[-8577756.329388095, 4715800.98615..."
3,3,"Takoma, Brightwood, Manor Park",Cluster 17,http://planning.dc.gov/,Original,NbhClusPly_4,{5BF4BCEC-5022-4B96-9577-C0246154197C},,,4,0,0,"{""rings"": [[[-8573179.697755544, 4717715.30026..."
4,4,Walter Reed,Cluster 40,,Additional,NbhClusPly_5,{C6705A7B-212E-419A-93CB-DA60707D0C37},,,5,0,0,"{""rings"": [[[-8575258.392574232, 4718520.22738..."

#### Checking the coordinate systems for the two Spatially Enabled DataFrames

This step ensures they are compatible for spatial operations.

In [12]:
sr_points = sedf_points.spatial.sr
sr_points

SpatialReference({'wkid': 4326})

In [13]:
sr_polygon = sedf_polygon.spatial.sr
sr_polygon

SpatialReference({'wkid': 102100, 'latestWkid': 3857})

#### Reprojecting one of the two datasets (if needed) to spatially join them in the same coordinate system

Skip this step and proceed to the next if both the datasets have identical values for `sr`

In [14]:
sedf_points.spatial.project(spatial_reference=sr_polygon)

True

#### Spatially joining the two Spatially Enabled DataFrames

In [15]:
joined_sedf = sedf_polygon.spatial.join(sedf_points, how='left')
joined_sedf.head()

,FID_left,NBH_NAMES,NAME,WEB_URL,TYPE,GIS_ID,GLOBALID,CREATED,EDITED,OBJECTID,...,SF,Status,PotentSite,MAR_LATITU,MAR_LONGIT,MAR_WARD,City,State,x,y
0,0,"Colonial Village, Shepherd Park, North Portal ...",Cluster 16,http://planning.dc.gov/,Original,NbhClusPly_1,{8D235E97-D58C-4891-943E-307143103BD9},,,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Rock Creek Park,Cluster 41,,Additional,NbhClusPly_2,{939C23A8-8EE2-4B4F-85EE-88281BCCC9A0},,,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"Hawthorne, Barnaby Woods, Chevy Chase",Cluster 10,http://planning.dc.gov/,Original,NbhClusPly_3,{8EADC8B8-3DAD-4E5D-AAF8-BF63D8316317},,,3,...,3200.0,Existing,No,38.9655,-77.0765,Ward 3,Washington,DC,-8.580117e+06,4.716731e+06
3,2,"Hawthorne, Barnaby Woods, Chevy Chase",Cluster 10,http://planning.dc.gov/,Original,NbhClusPly_3,{8EADC8B8-3DAD-4E5D-AAF8-BF63D8316317},,,3,...,33000.0,Existing,No,38.9646,-77.0749,Ward 3,Washington,DC,-8.579939e+06,4.716602e+06
4,3,"Takoma, Brightwood, Manor Park",Cluster 17,http://planning.dc.gov/,Original,NbhClusPly_4,{5BF4BCEC-5022-4B96-9577-C0246154197C},,,4,...,103000.0,Existing,No,38.9621,-77.0273,Ward 4,Washington,DC,-8.574640e+06,4.716244e+06

#### Plotting on a map

In [16]:
map2 = gis.map()
joined_sedf.spatial.plot(map2)
map2.zoom_to_layer(joined_sedf)
map2

Map(extent={'spatialReference': SpatialReference({'wkid': 102100, 'latestWkid': 3857}), 'xmin': -8584936.33383…