In [1]:
from arcgis.gis import GIS
from arcgis.gis.admin import AGOLAdminManager

# Administering Your GIS Organizations Using ArcGIS API for Python

## Overview

- The ArcGIS ecosystem is vast
- Organizations can have multiple versions of any product or multiple products to manage
- How do you manage this?

## The Way of the Python

- The Python API allows administrators to manage, update and control what happens on your server
- Script from your favorite IDE or Notebook environment
- Cross platform support

### What can we do With ArcGIS Online?

## Getting Started

### Understand the `GIS` Object

The `GIS` object is the way users connect to ArcGIS Online and/or Enterprise

- It doesn't matter if you are an administrator of a user, we must start here.

#### Connecting to you `GIS`

The ArcGIS API for Python support multiple ways of connecting to the `GIS`, which is ArcGIS Online or ArcGIS Enterprise

##### Anonymously

In [2]:
import pandas as pd
from arcgis.gis import GIS
gis = GIS() #anonymous connection

##### Built-In

- username/password login method
- usersname are case sensitive

```python
gis = GIS(username='fakeaccount', password='fakepassword')
gis = GIS(url="https://www.mysite.com/portal", username='fakeaccount', password='fakepassword')
```

**Protecting Built-In Credentials**

- using `profiles` will help protect username and passwords.  
- prevents accidental sharing

1. Create a `GIS` object with the extra `profile` parameter

```python
gis = GIS(url="https://www.mysite.com/portal", 
          username='fakeaccount', 
          password='fakepassword', 
          profile='portal_profile')
```

2. Now connect using the `profile`

```python
gis = GIS(profile='portal_profile')
```

**What Happened?**

Instead of keeping your password in plain text, now we leverage the operating system's credential store for the logged in user.  The credentials never get passed on when you use profiles.

## Developer Credentials

- There are two types of credentials:
    - API Keys - provide a long lived token with a set of privileges or actions
    - Application Authentication - a limited set of privileges scopes to a given web application normally

#### Creating API Keys

In [3]:
from arcgis.gis import GIS
gis = GIS(profile='your_online_profile', trust_env=True)
gis.users.me

##### Access the Administration Endpoint

In [4]:
from arcgis.gis.admin import AGOLAdminManager
from arcgis.gis.admin._stokenmgr import  TokenPrivilege
import datetime as _dt
admin:AGOLAdminManager = gis.admin
dev_creds = admin.developer_credentials

##### Create a Scoped API Key

In this scenerio, we are going to create an API key to allow a user to login via a token to view and create items.  We will define the privilege scope and set an expiration.

- Provide a `title`, `privileges`, `expiration` and `referer`
- The `expiration` can't be more than 1 year from now

In [5]:
api_credential = dev_creds.create(title='my first api key',
                                   privileges=[TokenPrivilege.PORTAL_ADMIN_VIEWITEMS, 
                                               TokenPrivilege.PORTAL_USER_CREATEITEM],
                                   referers=['http'],
                                   expiration=_dt.datetime.now() + _dt.timedelta(weeks=20))
api_credential

Creating an empty item.

In [6]:
token = api_credential.generate_token(slot=1)
token

{'access_token': 'AAPTxy8BH1VEsoebNVZXo8HurC_XeT3pOmZHnOyc93cCDQQRmt1hI7s2G8o8acsnlsV0Fpsxm8vp7Qmm6-gch2SBTF9ZJ_PEKeM6UcBeoX2Rp0PTbHFx9o5PpjmwiOly0eR1MjYRXAymWSBiQJhZsU9_nGjWK4xiyBtSDnyOfCHRRmAKA_sn641rCugkSkFnepedBcGclNlT3E1MPQYkEiATiLZKOeWdKel7f-tQDmtfOGM.AT1_PwBfTYt8',
 'expires_in': 15721139}

In [7]:
GIS(token=token['access_token']).users.me

In [8]:
api_credential.delete()

True

## User Management

Users fuel your system. As an administrator your job is to ensure they can put up there content and know the site is reliable and safe.  The Python API is a tool to do just that!

In [9]:
from arcgis.gis import GIS
gis = GIS(profile='your_online_profile', verify_cert=False)

Setting `verify_cert` to False is a security risk, use at your own risk.

### Working with Existing Users

In [10]:
um = gis.users
um

< UserManager at https://geosaurus.maps.arcgis.com >

In [11]:
um

Type:        UserManager
String form: < UserManager at https://geosaurus.maps.arcgis.com >
File:        ~/miniconda3/envs/dec15_daily/lib/python3.13/site-packages/arcgis/gis/__init__.py
Docstring:
The ``UserManager`` class is a helper class for managing GIS users. This class is not created by users directly.
An instance of this class, called 'users', is available as a property of the Gis object.
Users call methods on this 'users' object to manipulate (create, get, search, etc) users.

#### Search for Users

In [12]:
users = um.search("geo*")
users

[<User username:geosaurus_hub>,
 <User username:geosaurusaccnt_geosaurus>,
 <User username:nbda_user_50b0>,
 <User username:nbda_user_51d1>,
 <User username:nbda_user_9c6a>,
 <User username:nbda_user_a720>,
 <User username:nbda_user_eb59>]

### Advanced Search for Users

- Advanced Search gives your the full control to look up users.
- When using this search, nothing is there to guide you, so the queries are made by the end user.
- Provides the ability to get user counts and return users as dictionaries

##### How Many Users are in your Organization?

In [13]:
um.advanced_search(f"accountid:{gis.properties.id}", return_count=True)

96

##### Write Users to CSV File

In [14]:
import csv
csv_file = './data/output.csv'
field_names:list = None
results = um.advanced_search(f"accountid:{gis.properties.id}", as_dict=True,max_users=-1)
field_names = list(results.get("results")[0].keys()) + ['description']
with open(csv_file, 'w', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=field_names)
    writer.writeheader()
    for user in results['results']:
        writer.writerow(user)

#### List User's Groups

In [15]:
um.user_groups(um.search("dev*")[:2])

[{'username': 'andrew57',
  'total': 67,
  'groups': [{'id': '019671d6889641caaa62666df9b35740',
    'title': 'parntered collab test'},
   {'id': '03871c826cff466fa6015f1163677830', 'title': 'Shared Update Group'},
   {'id': '09a73a911ea843cea083cfe70545ecf6', 'title': 'sdfgsdfgsdfh Content'},
   {'id': '0c04228089a243149a503922ae17901c',
    'title': 'sdfgsdfg343gsdfghsdfhash Core Team'},
   {'id': '0c27e80243984ae2946c4f43ceb94115', 'title': 'Name'}]},
 {'username': 'arcgis_python',
  'total': 58,
  'groups': [{'id': '00df55a8a6324c5aa4fc946d01aebb01',
    'title': 'Gallery',
    'thumbnail': 'Gallery.png'},
   {'id': '0352e4178bb24751847ef9798abb6976', 'title': 'Agriculturey'},
   {'id': '03587dc5f53b45669448b873d3fdcf43',
    'title': 'Network Operations',
    'thumbnail': 'NetworkOperations.png'},
   {'id': '0d753a8388a74d8798b47db800f8023e',
    'title': 'Site from Intro NB API Content'},
   {'id': '10753adc0d4a4649b497b2fb28ad6483',
    'title': 'demo-workforce-project'}]}]

#### Access a User's Items

- At 2.4.1+ this returns a Generator
- A generator is a special type of function or expression that creates an iterator, allowing for the generation of values on demand instead of constructing an entire sequence in memory at once.

In [16]:
users[0].items()

In [17]:
for item in users[0].items():
    print(item)
    break

<Item title:"site2Apr4" type:Hub Site Application owner:geosaurus_hub>

### Creating New Users

In [18]:
# Check the user types available
um.counts('user_type')

                    key  count
0            advancedUT     13
1             creatorUT     71
2  GISProfessionalAdvUT     10
3  GISProfessionalStdUT      2

In [19]:
import uuid
username = f"RUser{uuid.uuid4().hex[:4]}"
password = f"!{uuid.uuid4().hex[:8]}A"
um = gis.users
new_user = um.create(username=username, password=password, 
                     firstname="Johnny", lastname="Human", 
                     email='testsadf@esri.com', 
                     role="org_publisher")
new_user

username, password

In [20]:
new_password = f"!{uuid.uuid4().hex[:8]}A"

#### Reset the Password

In [21]:
new_user.reset(
    password=password,
    new_password=new_password,
    new_security_question=1,
    new_security_answer=uuid.uuid4().hex[:10],
    reset_by_email=False,
)

True

In [22]:
GIS(username=username, 
    password=new_password, 
    verify_cert=False).users.me

Setting `verify_cert` to False is a security risk, use at your own risk.

#### Deleting the User

In [23]:
new_user.delete()

True

### Working with Roles and User Types

#### User types

- User type determines the privileges that can be granted to the member through a default or custom role
- Common Roles:
  + viewer, creator and administrator

In [24]:
user = gis.users.me

In [25]:
user.user_types()['id']

'GISProfessionalAdvUT'

In [26]:
user.update_license_type("creatorUT")

True

In [27]:
user.user_types()['id']

'creatorUT'

In [28]:
user.update_license_type("GISProfessionalAdvUT")
user.user_types()['id']

'GISProfessionalAdvUT'

#### Working with Roles

- A role defines the set of privileges assigned to a member

**Accessing Role Manager**

In [29]:
rm = gis.users.roles
rm

**Listing Roles**

In [30]:
rm.all()

[<Role name: Viewer, description: Viewer>,
 <Role name: Data Editor, description: Data Editor>,
 <Role name: Facilitator, description: Facilitator>,
 <Role name: role_b3721, description: description>,
 <Role name: role_b35ff, description: description>,
 <Role name: role_7ea92, description: description>,
 <Role name: role_b74eb, description: description>,
 <Role name: role_52997, description: description>,
 <Role name: role_569c6, description: description>,
 <Role name: role_3819a, description: description>,
 <Role name: role_f07f2, description: description>,
 <Role name: role_7a57a, description: description>,
 <Role name: role_55dae, description: description>,
 <Role name: role_ceb8a, description: description>,
 <Role name: role_c9cb9, description: description>,
 <Role name: role_eb600, description: description>,
 <Role name: role_f2e02, description: description>,
 <Role name: role_5e937, description: description>,
 <Role name: role_7c854, description: description>,
 <Role name: role_f586d, description: description>,
 <Role name: role_9a7cd, description: description>,
 <Role name: role_e3de0, description: description>,
 <Role name: role_64ad9, description: description>,
 <Role name: role_8ad64, description: description>,
 <Role name: role_b7935, description: description>,
 <Role name: role_f7eee, description: description>,
 <Role name: role_41265, description: description>,
 <Role name: role_73b92, description: description>,
 <Role name: role_1fbc4, description: description>,
 <Role name: role_d14d5, description: description>,
 <Role name: role_8f5d0, description: description>,
 <Role name: role_7dbea, description: description>,
 <Role name: role_dd58b, description: description>,
 <Role name: role_da1fc, description: description>,
 <Role name: role_67db7, description: description>,
 <Role name: role_e63f9, description: description>,
 <Role name: role_3289a, description: description>,
 <Role name: role_5a2a4, description: description>,
 <Role name: role_11a72, description: description>,
 <Role name: role_a0f82, description: description>,
 <Role name: role_e0745, description: description>,
 <Role name: role_4210c, description: description>,
 <Role name: role_17f6c, description: description>,
 <Role name: role_12996, description: description>,
 <Role name: role_3a934, description: description>,
 <Role name: role_e77a4, description: description>,
 <Role name: role_5152a, description: description>,
 <Role name: role_7b232, description: description>,
 <Role name: role_70002, description: description>,
 <Role name: role_40d11, description: description>,
 <Role name: role_58828, description: description>,
 <Role name: role_cca7d, description: description>,
 <Role name: role_2f238, description: description>,
 <Role name: role_7516f, description: description>,
 <Role name: role_9c505, description: description>,
 <Role name: role_6cd93, description: description>,
 <Role name: role_2a037, description: description>,
 <Role name: role_6a3e6, description: description>,
 <Role name: role_8dc85, description: description>,
 <Role name: role_81461, description: description>,
 <Role name: role_e4dc4, description: description>,
 <Role name: role_7f620, description: description>,
 <Role name: role_32da8, description: description>,
 <Role name: role_dcd92, description: description>,
 <Role name: role_e4a78, description: description>,
 <Role name: role_6472a, description: description>,
 <Role name: role_8b81e, description: description>,
 <Role name: role_41a6e, description: description>,
 <Role name: role_58b54, description: description>,
 <Role name: role_143f7, description: description>,
 <Role name: role_0878f, description: description>,
 <Role name: role_6891e, description: description>,
 <Role name: role_e14ec, description: description>,
 <Role name: AGOLImageryAnalysis, description: AGOLImageryAnalysis>,
 <Role name: role_450c7, description: description>,
 <Role name: role_9cdb6, description: description>,
 <Role name: role_e4f30, description: description>,
 <Role name: role_c1dcf, description: description>,
 <Role name: role_0133f, description: description>,
 <Role name: role_d843d, description: description>,
 <Role name: AllNotebookPrivileges, description: All Notebook Privileges>,
 <Role name: role_922ae, description: description>,
 <Role name: role_4af03, description: description>,
 <Role name: role_71395, description: description>,
 <Role name: role_dd772, description: description>,
 <Role name: role_d31c1, description: description>,
 <Role name: role_66568, description: description>,
 <Role name: role_21132, description: description>,
 <Role name: role_d2d2d, description: description>,
 <Role name: role_f6f87, description: description>,
 <Role name: role_ac8fe, description: description>,
 <Role name: UC2018_GEOG471, description: Special Role for Students enrolled in GEOG471>,
 <Role name: role_c782a, description: description>,
 <Role name: role_e4191, description: description>,
 <Role name: role_80bcc, description: description>,
 <Role name: role_6c89e, description: description>,
 <Role name: role_aa1ab, description: description>,
 <Role name: role_9f042, description: description>,
 <Role name: role_53fd8, description: description>,
 <Role name: role_c2249, description: description>,
 <Role name: role_f2da1, description: description>,
 <Role name: role_01de3, description: description>,
 <Role name: role_f6f2c, description: description>,
 <Role name: role_79fcc, description: description>,
 <Role name: role_22ffb, description: description>,
 <Role name: role_ab2f0, description: description>,
 <Role name: role_de2f7, description: description>,
 <Role name: role_fd2b5, description: description>,
 <Role name: role_6ae7a, description: description>,
 <Role name: role_1e6a3, description: description>,
 <Role name: role_8263e, description: description>,
 <Role name: role_afac4, description: description>,
 <Role name: role_f4614, description: description>,
 <Role name: role_32932, description: description>,
 <Role name: role_1335f, description: description>,
 <Role name: role_ec38f, description: description>,
 <Role name: role_5ee4c, description: description>,
 <Role name: role_93d06, description: description>,
 <Role name: role_8cfb8, description: description>,
 <Role name: role_2fd43, description: description>,
 <Role name: role_97c7d, description: description>,
 <Role name: role_bb41e, description: description>,
 <Role name: tiles_publisher, description: User that can publish tile layers>,
 <Role name: role_3dcce, description: description>,
 <Role name: role_ef477, description: description>,
 <Role name: role_9c51c, description: description>,
 <Role name: role_4bc46, description: description>,
 <Role name: role_e9e9c, description: description>,
 <Role name: role_dffc1, description: description>,
 <Role name: role_d83c7, description: description>,
 <Role name: role_8280f, description: description>,
 <Role name: role_40de8, description: description>,
 <Role name: role_77bd9, description: description>,
 <Role name: role_c950c, description: description>,
 <Role name: role_9dd21, description: description>,
 <Role name: role_c4f87, description: description>,
 <Role name: role_73887, description: description>,
 <Role name: role_2e96c, description: description>,
 <Role name: role_4f909, description: description>,
 <Role name: role_28c06, description: description>,
 <Role name: role_166e2, description: description>,
 <Role name: role_073ad, description: description>,
 <Role name: role_e4af7, description: description>,
 <Role name: role_166c0, description: description>,
 <Role name: role_4e77c, description: description>,
 <Role name: role_c249f, description: description>,
 <Role name: role_33bb6, description: description>,
 <Role name: role_bb284, description: description>,
 <Role name: role_5c459, description: description>,
 <Role name: role_782a2, description: description>,
 <Role name: role_f2d9d, description: description>,
 <Role name: role_fa490, description: description>,
 <Role name: role_4427b, description: description>,
 <Role name: role_c75eb, description: description>,
 <Role name: Run web tools , description: Run web tools privilege test.>,
 <Role name: role_03185, description: description>,
 <Role name: role_d71cd, description: description>,
 <Role name: role_20dce, description: description>,
 <Role name: role_acdcc, description: description>,
 <Role name: role_8f85f, description: description>,
 <Role name: role_c0dc1, description: description>,
 <Role name: role_ba15c, description: description>,
 <Role name: role_b30ad, description: description>,
 <Role name: role_8448f, description: description>,
 <Role name: role_99ff5, description: description>,
 <Role name: role_18b09, description: description>,
 <Role name: role_b0b35, description: description>,
 <Role name: role_bfbbf, description: description>,
 <Role name: role_42160, description: description>,
 <Role name: role_74569, description: description>,
 <Role name: role_c5f4b, description: description>,
 <Role name: role_134b0, description: description>,
 <Role name: role_109cd, description: description>,
 <Role name: role_e313e, description: description>,
 <Role name: role_9ed09, description: description>,
 <Role name: role_9b265, description: description>,
 <Role name: role_d984b, description: description>,
 <Role name: role_84160, description: description>,
 <Role name: role_4cfb0, description: description>,
 <Role name: role_cae64, description: description>,
 <Role name: role_3322c, description: description>,
 <Role name: role_40df9, description: description>,
 <Role name: role_4200a, description: description>,
 <Role name: role_0516f, description: description>,
 <Role name: role_f6beb, description: description>,
 <Role name: role_c561f, description: description>,
 <Role name: role_4f0e5, description: description>,
 <Role name: test_role, description: test>,
 <Role name: role_5c347, description: description>,
 <Role name: role_adf45, description: description>,
 <Role name: role_ee225, description: description>,
 <Role name: role_de8a9, description: description>,
 <Role name: role_491bb, description: description>,
 <Role name: role_bc6d7, description: description>,
 <Role name: role_03902, description: description>,
 <Role name: role_86d77, description: description>,
 <Role name: role_ed52d, description: description>,
 <Role name: role_2c24b, description: description>,
 <Role name: role_e24d2, description: description>,
 <Role name: role_fcb24, description: description>,
 <Role name: role_d8d6e, description: description>,
 <Role name: role_63ab1, description: description>,
 <Role name: role_aa1f4, description: description>,
 <Role name: role_f9ab7, description: description>,
 <Role name: role_bc0fd, description: description>,
 <Role name: role_b68fb, description: description>,
 <Role name: role_481c6, description: description>,
 <Role name: role_64bc1, description: description>,
 <Role name: role_13ba6, description: description>,
 <Role name: role_ba1d0, description: description>,
 <Role name: role_ce76d, description: description>,
 <Role name: role_5fef0, description: description>,
 <Role name: role_5d8ab, description: description>,
 <Role name: role_dce63, description: description>,
 <Role name: role_b42a0, description: description>,
 <Role name: role_29f4b, description: description>,
 <Role name: role_915c5, description: description>,
 <Role name: role_fd8dd, description: description>,
 <Role name: role_f46e0, description: description>,
 <Role name: role_e5c8e, description: description>,
 <Role name: role_775b6, description: description>,
 <Role name: role_f3f5d, description: description>,
 <Role name: role_02362, description: description>,
 <Role name: role_6ff4b, description: description>,
 <Role name: role_5d44d, description: description>,
 <Role name: role_1bb21, description: description>,
 <Role name: role_e4fb7, description: description>,
 <Role name: role_dbf9e, description: description>,
 <Role name: role_f4796, description: description>,
 <Role name: role_782d1, description: description>,
 <Role name: role_138a4, description: description>,
 <Role name: role_847bb, description: description>,
 <Role name: role_8a3a5, description: description>,
 <Role name: role_c66cb, description: description>,
 <Role name: role_30743, description: description>,
 <Role name: role_7ee87, description: description>,
 <Role name: role_39be6, description: description>,
 <Role name: role_8e5bf, description: description>,
 <Role name: role_fb82d, description: description>,
 <Role name: advanced notebooks, description: advanced notebooks>,
 <Role name: role_73abb, description: description>,
 <Role name: role_84d47, description: description>,
 <Role name: role_d50da, description: description>,
 <Role name: role_7ead0, description: description>,
 <Role name: role_4257d, description: description>,
 <Role name: role_c1fcc, description: description>,
 <Role name: role_27afe, description: description>,
 <Role name: role_2d516, description: description>,
 <Role name: role_9673b, description: description>,
 <Role name: role_0e147, description: description>,
 <Role name: role_a8485, description: description>,
 <Role name: role_4f57d, description: description>,
 <Role name: role_ffd47, description: description>,
 <Role name: role_9e2c8, description: description>,
 <Role name: role_b67fd, description: description>,
 <Role name: role_5623d, description: description>,
 <Role name: role_d899b, description: description>,
 <Role name: role_3e805, description: description>,
 <Role name: role_edec9, description: description>,
 <Role name: role_460e3, description: description>,
 <Role name: role_13a14, description: description>,
 <Role name: role_87780, description: description>,
 <Role name: role_6cc22, description: description>,
 <Role name: role_ade8a, description: description>,
 <Role name: role_280ec, description: description>,
 <Role name: role_0c05c, description: description>,
 <Role name: test_minimum_gui, description: role created in gui to see what happens>,
 <Role name: role_77ca3, description: description>,
 <Role name: role_d77e0, description: description>,
 <Role name: role_a2a9d, description: description>,
 <Role name: role_49329, description: description>,
 <Role name: role_e9c6a, description: description>,
 <Role name: role_9ef03, description: description>,
 <Role name: role_8043b, description: description>,
 <Role name: role_15d81, description: description>,
 <Role name: role_f3684, description: description>,
 <Role name: role_95e4e, description: description>,
 <Role name: role_9f87f, description: description>,
 <Role name: role_ef952, description: description>,
 <Role name: role_10989, description: description>,
 <Role name: role_1c6ae, description: description>,
 <Role name: role_d3bde, description: description>,
 <Role name: role_25ec5, description: description>,
 <Role name: role_2b5f8, description: description>,
 <Role name: role_53de4, description: description>,
 <Role name: role_7cef3, description: description>,
 <Role name: role_a93d9, description: description>,
 <Role name: role_292f7, description: description>,
 <Role name: role_7a29a, description: description>,
 <Role name: role_3331b, description: description>,
 <Role name: role_9fb36, description: description>,
 <Role name: role_14c07, description: description>,
 <Role name: role_4fa4f, description: description>,
 <Role name: role_51f61, description: description>,
 <Role name: role_7cb11, description: description>,
 <Role name: role_0bc63, description: description>,
 <Role name: role_07670, description: description>,
 <Role name: role_59187, description: description>,
 <Role name: role_2dfca, description: description>,
 <Role name: role_6ed92, description: description>,
 <Role name: role_20c11, description: description>,
 <Role name: role_f9914, description: description>,
 <Role name: role_7969d, description: description>,
 <Role name: role_ee81f, description: description>,
 <Role name: role_6aa35, description: description>,
 <Role name: role_a79b1, description: description>,
 <Role name: role_680c4, description: description>,
 <Role name: role_2c74b, description: description>,
 <Role name: role_b6e53, description: description>,
 <Role name: role_9bc82, description: description>,
 <Role name: role_5b496, description: description>,
 <Role name: role_f8fa0, description: description>,
 <Role name: role_80018, description: description>,
 <Role name: role_67e75, description: description>,
 <Role name: role_27726, description: description>,
 <Role name: role_cb21e, description: description>,
 <Role name: role_035bb, description: description>,
 <Role name: role_1473c, description: description>,
 <Role name: role_4f62e, description: description>,
 <Role name: role_ece8a, description: description>,
 <Role name: role_af93f, description: description>,
 <Role name: role_8511a, description: description>,
 <Role name: role_a8264, description: description>,
 <Role name: role_20b3f, description: description>,
 <Role name: role_ec101, description: description>,
 <Role name: role_946ef, description: description>,
 <Role name: role_e4b98, description: description>,
 <Role name: role_1bc55, description: description>,
 <Role name: role_1cd25, description: description>,
 <Role name: role_0dae6, description: description>,
 <Role name: role_fcb11, description: description>,
 <Role name: role_9ea2a, description: description>,
 <Role name: role_a0ff8, description: description>,
 <Role name: role_bd762, description: description>,
 <Role name: role_a9716, description: description>,
 <Role name: role_be7db, description: description>,
 <Role name: role_26700, description: description>,
 <Role name: role_245a4, description: description>]

**Check for Existence of a Role**

In [31]:
rm.exists('DataEditorRole')

False

In [32]:
role = rm.create(name="DataEditorRole", 
                 description="Allow to modify service data", 
                 privileges=[
                        "features:user:edit",
                        "features:user:fullEdit",
                        "opendata:user:designateGroup",
                        "portal:admin:viewUsers",
                        "portal:user:createGroup"]
                )
role

**Removing the Role**

In [33]:
role.delete()

True

## Managing Content

In [34]:
cm = gis.content
cm

### Working with Content

**The content manager allows users and administrators to work with, find and manage content**

#### Searching

##### `search` Example

- provides a simple search method
- max items is 10,000
- do not have full control over searches

In [35]:
cm.search(query="title: battle", item_type="Feature Layer", outside_org=False)

[]

In [36]:
cm.search(query="title: battle", item_type="Feature Layer", outside_org=True)

[<Item title:"Civil_War_Battles" type:Feature Layer Collection owner:t3g09_BarbareeDuke>,
 <Item title:"HLL_Battle_App___Front_Lines_HF" type:Feature Layer Collection owner:topher303>,
 <Item title:"Density Based Clustering Time _10_ 1__WFL1" type:Feature Layer Collection owner:mcovey1_GISandData>,
 <Item title:"ACLED Nigeria Event Layers" type:Feature Layer Collection owner:K1060493@NZDF.MIL.NZ_nzdf>,
 <Item title:"MS_USH_IM_T09_L05_001M_N view" type:Feature Layer Collection owner:skktracy>,
 <Item title:"Last day Battle of the Alamo _1836__ 3D_WSL3" type:Feature Layer Collection owner:157_275_1923_9_byui>,
 <Item title:"1835_TXRev_Interactive_Webmap_WFL1" type:Feature Layer Collection owner:lynnette.cen@glo.texas.gov>,
 <Item title:"Key US Civil War Battles" type:Feature Layer Collection owner:Esri_GeoInquiry_History>,
 <Item title:"5kmNearest_Site_Poteniels_to_Battles" type:Feature Layer Collection owner:LroyCWT>,
 <Item title:"Civil_War_Battles - Battles_1861" type:Feature Layer Collection owner:CP4510Students_gtmaps>]

##### `advanced_search` Example

- full control searching option
- removed limitations of `search`
- returns items as dictionary, which speeds up searches
- leverage system for simple statistics about content

**How Many Item to Examine?**

In [37]:
count = cm.advanced_search('title: battle AND  (type:"feature service")', return_count=True)
count

985

In [38]:
items = cm.advanced_search('title: battle AND  (type:"feature service")', max_items=count, 
                           sort_field='avgRating', sort_order='desc')['results']
items[10:20]

[<Item title:"1861 Civil War Battles" type:Feature Layer Collection owner:GaDOE_SocialStudies_K-5_Atlas>,
 <Item title:"Shenandoah Valley Battlefields" type:Feature Layer Collection owner:allison.tillett_vdcr>,
 <Item title:"Civil War - All Battles as Hotspot Map (1861-1865)" type:Feature Layer Collection owner:BucknellGIS>,
 <Item title:"CivilWarP2A" type:Feature Layer Collection owner:chris.bun_madisonschools>,
 <Item title:"Civil War Battles Won by North" type:Feature Layer Collection owner:BucknellGIS>,
 <Item title:"ukraine battles 2022 Wk_12345" type:Feature Layer Collection owner:KHANW6@farmingdale.edu_FarmingdaleSC>,
 <Item title:"Predator Control Map_WFL1" type:Feature Layer Collection owner:ENMbiodiversity>,
 <Item title:"Nigeria ID change_WFL1" type:Feature Layer Collection owner:jacksontx2013>,
 <Item title:"UsHist_Virginia_features" type:Feature Layer Collection owner:Maps.com_carto>,
 <Item title:"Summarizes_Key_US_Civil_War_Battles_in_Cataloged_Desertion_Materials" type:Feature Layer Collection owner:cmarfia_CalPoly>]

**Gathering Information from Searches**

- In this demo we will see how much new content was added to the organization in the last 5 days.

In [39]:
import datetime as _dt

now =_dt.datetime.now(_dt.timezone.utc)
then = now - _dt.timedelta(days=5)

In [40]:
cm.advanced_search(
    f"created: [{int(then.timestamp()* 1000)} TO {int(now.timestamp()* 1000)}] AND accountid:{gis.properties.id}", 
    return_count=True)

61

#### Adding and Publishing Content

In [41]:
import uuid
username = f"FedUser{uuid.uuid4().hex[:3]}"
password = f"!{uuid.uuid4().hex[:6]}A"
user = gis.users.create(username=username,
        password=password,
        firstname=uuid.uuid4().hex[:6],
        lastname=uuid.uuid4().hex[:6],
        email=uuid.uuid4().hex[:6] + "@esri.com",
        role='org_publisher')
user

In [42]:
list(user.items())

[]

##### Publishing a Table

In this scenerio, the Administrator is going to add and publish a table to the newly created user from the previous steps.

In [43]:
import io, uuid
import pandas as pd
from arcgis.gis import ItemProperties, ItemTypeEnum

###### Load the Table into Memory

In [44]:
buffer = io.StringIO()
df = pd.read_csv("./data/banklist.csv")
df

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,26-Jul-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,26-Jul-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,26-Jul-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17
...,...,...,...,...,...,...,...
548,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB",27-Jul-01,19-Aug-14
549,Malta National Bank,Malta,OH,6629,North Valley Bank,3-May-01,18-Nov-02
550,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,2-Feb-01,18-Feb-03
551,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,14-Dec-00,17-Mar-05
552,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,13-Oct-00,17-Mar-05

In [45]:
df.to_csv(buffer)

###### Get the Destination User's Root Folder

In [46]:
folder = gis.content.folders.get(owner=user)
folder

< Folder: Root Folder Owner: FedUser778>

###### Populate the Item Properties and Add the Content

In [47]:
ip = ItemProperties(item_type=ItemTypeEnum.CSV, 
                    title='Failed Banks', 
                    file_name=f"failedbanks{uuid.uuid4().hex[:5]}.csv")
ip

In [48]:
result = folder.add(item_properties=ip, file=buffer)
result

< Job for Item: d0e75ca89c9742628e3b13fd5a422e18 >

In [49]:
item = result.result()
item

###### Analyze the Item and Publish the Table

In [50]:
analyzed = gis.content.analyze(item=item)
publish_parameters = analyzed['publishParameters']
publish_parameters[
        'name'
    ] = f"Failed_Banks_{uuid.uuid4().hex[:2]}"  # this needs to be updated
publish_parameters['locationType'] = None  # this makes it a hosted table
published_item = item.publish(publish_parameters)

In [51]:
published_item

In [52]:
published_item.delete(permanent=True)
item.delete(permanent=True)

True

## Viewing All Content

- Administrators have  the ability to view **ALL** content on a given organization from the `gis.admin` endpoint

In [53]:
# View all Feature Services in a Given Organization
for item in gis.admin.content(item_type=ItemTypeEnum.FEATURE_SERVICE,
                           sort_field='created',
                           order='desc'):
    print(item)

<Item title:"calculate_density_point_data_885d" type:Table Layer owner:arcgis_python>
<Item title:"restaurants_123" type:Table Layer owner:arcgis_python>
<Item title:"aggregate_points_point_data_0f8f" type:Table Layer owner:arcgis_python>
<Item title:"aggregate_points_polygon_data_b87d" type:Feature Layer Collection owner:arcgis_python>
<Item title:"aggregate_points_point_data_8404" type:Table Layer owner:arcgis_python>
<Item title:"aggregate_points_polygon_data_f885" type:Feature Layer Collection owner:arcgis_python>
<Item title:"aggregate_points_point_data_90d8" type:Table Layer owner:arcgis_python>
<Item title:"aggregate_points_polygon_data_f29d" type:Feature Layer Collection owner:arcgis_python>
<Item title:"add_to_def_fl_e4b42" type:Feature Layer Collection owner:arcgis_python>
<Item title:"california_cities_6154" type:Feature Layer Collection owner:arcgis_python>
<Item title:"create_drive_time_areas_office_data_1070" type:Feature Layer Collection owner:arcgis_python>
<Item title:"Bear Creek Watershed_max" type:Feature Layer Collection owner:arcgis_python>
<Item title:"jy_Test_Join_VW_uf0we" type:Feature Layer Collection owner:jyaist_geosaurus>
<Item title:"find_outliers_data_61e0" type:Feature Layer Collection owner:arcgis_python>
<Item title:"jy_Test_Join_VW_wpRf2" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"Atlanta_Buildings_SalesJoin_v3" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"Atlanta_Buildings_SalesJoin_v2" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"Atlanta_Businesses_2026" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"Minerville muliple tables" type:Feature Layer Collection owner:jyaist_geosaurus>
<Item title:"jy_Test_Join_VW_RhpSD" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"jy_Test_Join_VW_UEN9X" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"ntgrtn_tst_user_content_1770094123" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"JoinVw_fire_stations_to_fire_districts" type:Feature Layer Collection owner:jyaist_geosaurus>
<Item title:"sedf_overwrite_poly_item_c6ac2" type:Feature Layer Collection owner:arcgis_python>
<Item title:"sedf_overwrite_pt_item_c6ac2" type:Feature Layer Collection owner:arcgis_python>
<Item title:"sedf_overwrite_26e6d" type:Table Layer owner:arcgis_python>
<Item title:"Tussock Near Campgrounds_h923" type:Feature Layer Collection owner:arcgis_python>
<Item title:"Houston_target_join" type:Feature Layer Collection owner:jyaist_geosaurus>
<Item title:"Houston_Join2" type:Feature Layer Collection owner:jyaist_geosaurus>
<Item title:"Washington State Hospitals" type:Feature Layer Collection owner:jyaist_geosaurus>
<Item title:"Summarize_Within_Poly_Result3" type:Feature Layer Collection owner:andrew57>
<Item title:"Summarize_Within_Poly_Result2" type:Feature Layer Collection owner:andrew57>
<Item title:"gcode_test_file" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"dino_ContentManager_test_add_csv" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"Trees" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"MapAndTable_gdb" type:Feature Layer Collection owner:naubry_geosaurus>
<Item title:"Trees" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"TX_reservoirs_recent_6hd4g view" type:Feature Layer Collection owner:arcgis_python>
<Item title:"TX_reservoirs_recent_6hd4g" type:Feature Layer Collection owner:arcgis_python>
<Item title:"Test_Join_m2Y1M" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"New_Join_View2" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"New_Join_View" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"MarineLife_STGL_And_STGL_RelatedTables" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"Layer_1 view" type:Feature Layer Collection owner:arcgis_python>
<Item title:"Layer_1" type:Feature Layer Collection owner:arcgis_python>
<Item title:"Layer_1 view" type:Feature Layer Collection owner:arcgis_python>
<Item title:"Layer_1" type:Feature Layer Collection owner:arcgis_python>
<Item title:"Layer_1 view" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"Layer_1" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"Layer_1_view_4fda8_f6113" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"Layer_1" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"Flight delay 2025  ATL" type:Feature Layer Collection owner:api_data_owner>
<Item title:"Flight Delay 2025 MSP" type:Feature Layer Collection owner:api_data_owner>
<Item title:"iowa_corn" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"kuytky" type:Feature Layer Collection owner:andrew57>
<Item title:"ports_jy" type:Feature Layer Collection owner:jyaist_geosaurus>
<Item title:"Nigeria_Subtype_no_stgl" type:Feature Layer Collection owner:jyaist_geosaurus>
<Item title:"ntgrtn_tst_user_content_1764823827" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"test_generate_tessellation_0317" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"overwrite_test_interpolate_34df" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"test_join_polygon_point_4dae" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"test_join_features_af67" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"US airports" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"test_join_features_df46" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Hospitals" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"test_composite_index_8899" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"overwrite_dissolve_boundaries_b189" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"overwrite_dissolve_boundaries_eb5b" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"summarize_within_hexagons" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"summarize_within_squares" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"overwrite_test_trace_downstream_f7b8" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"overwrite_test_trace_downstream_06f1" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"test_summarize_within_40b4" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"summarize_within_small_point_data_2e35" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"nyc_enriched_school_districts" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"NYC_School_Districts" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"PovertyVariables_GreaterLA_2017to2021" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"similar_locations_ui" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"maryland_cities_04f8" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"california_cities_1e93" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"test_summarize_within_5bf4" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"test_summarize_nearby_ed5d" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"AL_stgl" type:Feature Layer Collection owner:jyaist_geosaurus>
<Item title:"overwrite_summarize_center_and_dispersion_cddd" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"test_plan_routes_b11a" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"test_overlay_layers_379b" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"test_merge_layers_9297" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"create_route_layers_data_1f85" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Ghana_Level1_Admin" type:Feature Layer Collection owner:jyaist_geosaurus>
<Item title:"overwrite_find_outliers_a29" type:Feature Layer Collection owner:andrew57>
<Item title:"overwrite_find_hot_spots_b88c" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Charlotte Fictitious Parks" type:Feature Layer Collection owner:naubry_geosaurus>
<Item title:"Charlotte Fictitious Parks" type:Feature Layer Collection owner:naubry_geosaurus>
<Item title:"test_find_nearest_06f7" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"dest_dataset_b684" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"origin_dataset_f7b1" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"test_find_existing_location_e995" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"viewshed_1811" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"census_block_groups_orange_county" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"census_block_groups_california" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"California_Counties" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"D1_D2_D3_Buildings_1" type:Feature Layer Collection owner:api_data_owner>
<Item title:"Philly_MV_Theft_HotSpots" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"Philly_MV_Thefts" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"Trees" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"overwrite_enrich_layer_934292" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"overwrite_test_new_locations_727384" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"derive_new_locations_data_65c8" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Trees" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"Minnesota Wells Database" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"census_blocks_ntgrtn_tst_gdb" type:Feature Layer Collection owner:api_data_owner>
<Item title:"overwrite_test_create_watersheds_385398" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Minnesota Wells Database" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"viewshed_335781" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"viewshed_data_554326" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"overwrite_test_origin_to_destination_242476" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"overwrite_test_origin_to_destination_363759" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Workforce-ntgrtn-tst_d319a" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"swap data source" type:Feature Layer Collection owner:andrew57>
<Item title:"create_view_fields_selected" type:Feature Layer Collection owner:andrew57>
<Item title:"create_view_aoi" type:Feature Layer Collection owner:andrew57>
<Item title:"create_view_attribute_filter" type:Feature Layer Collection owner:andrew57>
<Item title:"view_nothing_special" type:Feature Layer Collection owner:andrew57>
<Item title:"RNF_MP_10th_MajorRoutes_gdb" type:Feature Layer Collection owner:andrew57>
<Item title:"Worcester_Coffee" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"Trees_WashingtonDC" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"Mass_hospitals_NG" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"Philly_neighborhood_retail_NG" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"Workforce-ntgrtn-tst_14e3b" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"Workforce-ntgrtn-tst_48f26" type:Feature Layer Collection owner:arcgis_python>
<Item title:"ntgrtn_tst_user_content_1761282391" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"USA_Major_Cities" type:Feature Layer Collection owner:andrew57>
<Item title:"Hamburg Districts (New)" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"feature_data_gdb view" type:Feature Layer Collection owner:naubry_geosaurus>
<Item title:"feature_data_gdb" type:Feature Layer Collection owner:naubry_geosaurus>
<Item title:"feature_data2_gdb" type:Feature Layer Collection owner:naubry_geosaurus>
<Item title:"Rome 2 view" type:Feature Layer Collection owner:naubry_geosaurus>
<Item title:"Rome view" type:Feature Layer Collection owner:naubry_geosaurus>
<Item title:"ae70a8.zip" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"webhook_data_fgdb_1759901939" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"CA/OR Airports" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"fgdhfgnxbn" type:Feature Layer Collection owner:andrew57>
<Item title:"sfdgdfdata" type:Feature Layer Collection owner:andrew57>
<Item title:"gsdfgsfdg" type:Feature Layer Collection owner:andrew57>
<Item title:"create_viewshed_data1" type:Feature Layer Collection owner:andrew57>
<Item title:"python_choose_best_facilities1" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"test_choose_best_facilities" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"US_Regional_Offices" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Esri_Headquarters" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"aabefb.zip" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"created_from_dict_xyJm" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"overwrite_drivetime_output" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"test_drivetimeareas" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"create_viewshed_restaurant1" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"create_viewshed_data2" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"create_viewshed_data1" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"create_viewshed_data" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"restaurants_test_data_manushi" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"AUS_sample_points" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"gbr_cities_density_result" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"density_restaurants_result" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"calculate_density_point_data_manushi_test" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"tl_2018_37_cousub" type:Feature Layer Collection owner:drewwock>
<Item title:"Prediction Layer" type:Feature Layer Collection owner:api_data_owner>
<Item title:"Arkansas Hospitals" type:Feature Layer Collection owner:api_data_owner>
<Item title:"ntgrtn_tst_user_content_1758646771" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"ntgrtn_tst_user_content_1758646638" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"Workforce-ntgrtn-tst_4ed4f" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"ERG_feature_layer" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"prediction_layer" type:Feature Layer Collection owner:api_data_owner>
<Item title:"example_view_7b7ec8" type:Feature Layer Collection owner:andrew57>
<Item title:"example_a_977795" type:Feature Layer Collection owner:andrew57>
<Item title:"Philly_MV_Theft_density1" type:Feature Layer Collection owner:andrew57>
<Item title:"Prediction Layer" type:Feature Layer Collection owner:api_data_owner>
<Item title:"OD_Cost_Matrix_Oct_2019" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"usa_census_blocks_for_testing view" type:Feature Layer Collection owner:arcgis_python>
<Item title:"usa_census_blocks_for_testing" type:Feature Layer Collection owner:arcgis_python>
<Item title:"Philly_Neighborhoods" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"fdsgdfgse34sdfg" type:Feature Layer Collection owner:andrew57>
<Item title:"aba60e.zip" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"ae4f32.zip" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"Arkansas Hospitals" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Arkansas Hospitals" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"Arkansas Hospitals" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Arkansas Hospitals" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"test_import_data dada" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"England temperature 6acb" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"England temperature 8abc" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"test_import_data 3b4d" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"test_import_data 7f2d" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"test_import_data 0fdc" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"test_import_data af66" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"England temperature 7a4b" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"England temperature da51" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"test_import_data abf0" type:Feature Layer Collection owner:ArcGISPyAPIBot>
<Item title:"BUG_Clone_Items_gdb" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"multipatch_web_layer2_2507251636" type:Feature Layer Collection owner:nparavicini_geosaurus>
<Item title:"Venice Structures" type:Feature Layer Collection owner:jyaist_geosaurus>
<Item title:"Venice_public_works" type:Table Layer owner:jyaist_geosaurus>
<Item title:"CapitolhillEnrichedByPop235549" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"EnrichByPop364418" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"ClipedBuffer325576" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"DissolvedLayers873231" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Merge2149612" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Merge191674" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"CapitolHillStreet470550" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Buffer23rd24thAveStreet329956" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"23rd24thAve675154" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"BufferBroadwayStreet129259" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Broadway10thAVE348655" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Broadway10thAVE579498" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"BufferMadisonStreet972689" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"MadisonStreet486681" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"ArterialStreets272579" type:Feature Layer Collection owner:MMajumdar_geosaurus>
<Item title:"Proclaimed_Forests_1m_acres" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"Nigeria water control subtype gl" type:Feature Layer Collection owner:jyaist_geosaurus>
<Item title:"Buffer zone" type:Feature Layer Collection owner:NGiner_geosaurus>
<Item title:"BuildingsWoolseyVisitStatus_filtered_sample_ExportFeatures" type:Feature Layer Collection owner:api_data_owner>
<Item title:"test_import_data c31b" type:Feature Layer Collection owner:ArcGISPyAPIBot>

KeyboardInterrupt:

## Metadata

- Administrators can enable metadata for the organization

In [54]:
mm = gis.admin.metadata
mm

< MetadataManager at https://geosaurus.maps.arcgis.com >

In [55]:
mm.enable()

True

In [56]:
mm.is_enabled

True